version: '3.9'
services:
  glances:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    pid: "host"
    privileged: true
    network_mode: "host"
    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro"
      - "/home/Hereux/glances.conf:/glances/conf/glances.conf"
    
    environment:
      - TZ="Europe/Berlin"
      - "GLANCES_OPT=-C /glances/conf/glances.conf -w"
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`glances.local`)"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
      - "traefik.http.services.glances.loadbalancer.server.scheme=http"
      - "traefik.docker.network=host"
